
GET http://localhost:8080/logout
### Get by ID
GET http://localhost:8080/books/65458d5a1bbe8583a4af7758
### Add a new book
POST http://localhost:8080/books
content-type: application/json

{
    "title": "The Eye of the World",
    "author": "Robert Jordan",
    "ranking": 5,
    "genre": "fantasy",
    "wordCount": 300147,
    "year": 1990,
    "series": "yes"
}


### Edit a book
PUT http://localhost:8080/books/653c2662f20d0f65f1df8e54
content-type: application/json

{
    "title": "The Eye of the World",
    "author": "Robert Jordan",
    "ranking": 5,
    "genre": "fantasy",
    "wordCount": 300147,
    "year": 1990,
    "series": "yes"
}

### Delete a book
DELETE http://localhost:8080/books/65458e8fca89adef5fc76bd9

### Get all render
GET https://favorites-gem3.onrender.com/books

### Get by ID render
GET https://favorites-gem3.onrender.com/books/652ae27fcd1740368fec5e1e

### Add a new book with render
POST https://favorites-gem3.onrender.com/books
content-type: application/json

{
    "title": "Yumi and the Nighmare Painter",
    "author": "Brandon Sanderson",
    "ranking": 5
}

### Edit a book using render
PUT https://favorites-gem3.onrender.com/books/65343d3973bece0c57b7dd26
content-type: application/json

{
    "title": "Yumi and the Nighmare Painter",
    "author": "Brandon Sanderson",
    "ranking": 4
}

### Delete a book using render
DELETE https://favorites-gem3.onrender.com/books/65343d3c73bece0c57b7dd27


###
###
### POST STATMENTS TO ADD DATA BACK IN ###
###
###


### BOOK 1
POST https://favorites-gem3.onrender.com/books
content-type: application/json

{
    "title": "The Way of Kings",
    "author": "Brandon Sanderson",
    "ranking": 4,
    "genre": "fantasy",
    "wordCount": 383389,
    "year": 2010,
    "series": "yes"
}

### BOOK 2
POST https://favorites-gem3.onrender.com/books
content-type: application/json

{
    "title": "Words of Radiance",
    "author": "Brandon Sanderson",
    "ranking": 2,
    "genre": "fantasy",
    "wordCount": 399431,
    "year": 2014,
    "series": "yes"
}

### BOOK 3
POST https://favorites-gem3.onrender.com/books
content-type: application/json

{
    "title": "Oathbringer",
    "author": "Brandon Sanderson",
    "ranking": 1,
    "genre": "fantasy",
    "wordCount": 451912,
    "year": 2017,
    "series": "yes"
}

### BOOK 4
POST https://favorites-gem3.onrender.com/books
content-type: application/json

{
    "title": "Rhythm of War",
    "author": "Brandon Sanderson",
    "ranking": 3,
    "genre": "fantasy",
    "wordCount": 455891,
    "year": 2020,
    "series": "yes"
}

### BOOK 5
POST https://favorites-gem3.onrender.com/books
content-type: application/json

{
    "title": "Yumi and the Nightmare Painter",
    "author": "Brandon Sanderson",
    "ranking": 6,
    "genre": "fantasy",
    "wordCount": 113455,
    "year": 2023,
    "series": "no"
}

### BOOK 6
POST https://favorites-gem3.onrender.com/books
content-type: application/json

{
    "title": "The Eye of the World",
    "author": "Robert Jordan",
    "ranking": 5,
    "genre": "fantasy",
    "wordCount": 300147,
    "year": 1990,
    "series": "yes"
}
