GET http://localhost:8080/favorites
### Get by ID
GET http://localhost:8080/favorites/652ae27fcd1740368fec5e1e
### Add a new book
POST http://localhost:8080/favorites
content-type: application/json

{
    "title": "Rhythm of War",
    "author": "Brandon Sanderson",
    "ranking": 5
}

### Edit a book
PUT http://localhost:8080/favorites/652b1aa0a8fb22579b4beff9
content-type: application/json

{
    "title": "Rhythm of War",
    "author": "Brandon Sanderson",
    "ranking": 4
}

### Delete a book
DELETE http://localhost:8080/favorites/653412b38882f6553b8a53eb

### Get all render
GET https://favorites-gem3.onrender.com/favorites

### Get by ID render
GET https://favorites-gem3.onrender.com/favorites/652ae27fcd1740368fec5e1e

### Add a new book with render
POST https://favorites-gem3.onrender.com/favorites
content-type: application/json

{
    "title": "Yumi and the Nighmare Painter",
    "author": "Brandon Sanderson",
    "ranking": 5
}

### Edit a book using render
PUT https://favorites-gem3.onrender.com/favorites/65343d3973bece0c57b7dd26
content-type: application/json

{
    "title": "Yumi and the Nighmare Painter",
    "author": "Brandon Sanderson",
    "ranking": 4
}

### Test
PUT https://favorites-gem3.onrender.com/favorites/65343d3973bece0c57b7dd26
content-type: application/json

{
    "title": "Yumi and the Nighmare Painter",
    "author": "Brandon Sanderson",
    "ranking": "STRING"
}

### Delete a book using render
DELETE https://favorites-gem3.onrender.com/favorites/65343d3c73bece0c57b7dd27
